import type { GroundedAnswer } from "../domain/contracts";

type Provenance = Pick<GroundedAnswer, "modelId" | "revision" | "origin">;

/** Online generation (ADR 0017) wrote it, not the model on this computer. */
export function isOnline(result: Provenance): boolean {
  return result.origin === "groq";
}

/**
 * Who wrote a summary or answer, for the line under it. An online result
 * never says "local"; a hosted model has no pinned revision to show.
 */
export function madeBy(result: Provenance, withRevision = false): string {
  if (isOnline(result)) return `Made online by Groq with ${result.modelId}`;
  const revision = withRevision
    ? ` (revision ${result.revision.slice(0, 12)})`
    : "";
  return `Made by the local model ${result.modelId}${revision}`;
}

/** The same, for a summary saved as a file. */
export function generatedBy(result: Provenance): string {
  return isOnline(result)
    ? `Generated online by Groq with ${result.modelId}`
    : `Generated by Folio's local model ${result.modelId} (revision ${result.revision.slice(0, 12)})`;
}
