import { describe, expect, it } from "vitest";
import { generatedBy, isOnline, madeBy } from "./generatedBy";

const local = { modelId: "qwen3-0.6b-q4", revision: "0123456789abcdef" };
const online = {
  modelId: "openai/gpt-oss-20b",
  revision: "hosted",
  origin: "groq" as const,
};

describe("generated result provenance", () => {
  it("keeps the local wording, with a revision only when asked", () => {
    expect(isOnline(local)).toBe(false);
    expect(madeBy(local)).toBe("Made by the local model qwen3-0.6b-q4");
    expect(madeBy(local, true)).toBe(
      "Made by the local model qwen3-0.6b-q4 (revision 0123456789ab)",
    );
    expect(generatedBy(local)).toBe(
      "Generated by Folio's local model qwen3-0.6b-q4 (revision 0123456789ab)",
    );
  });

  it("never calls an online result local", () => {
    expect(isOnline(online)).toBe(true);
    for (const text of [
      madeBy(online),
      madeBy(online, true),
      generatedBy(online),
    ]) {
      expect(text).toContain("online by Groq with openai/gpt-oss-20b");
      expect(text).not.toMatch(/local|revision/);
    }
  });
});
